language: node_js
node_js:
  - 7
services:
- docker

env:
  global:
    DOCKER_REPO=brunoribca/api-gateway

script:
  - docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master